import os
from dotenv import load_dotenv

ETHERSCAN_API_URL = os.getenv("ETHERSCAN_API_URL")
ETHERSCAN_API_KEY = os.getenv("ETHERSCAN_API_KEY")
ETHERSCAN_DELAY = float(os.getenv("ETHERSCAN_DELAY"))

MODEL_API_URL = os.getenv("MODEL_API_URL")
MODEL_NAME = os.getenv("MODEL_NAME")
MODEL_API_KEY = os.getenv("MODEL_API_KEY")

EXTRACTOR_MODEL_API_URL = os.getenv("EXTRACTOR_MODEL_API_URL")
EXTRACTOR_MODEL_NAME = os.getenv("EXTRACTOR_MODEL_NAME")
EXTRACTOR_MODEL_API_KEY = os.getenv("EXTRACTOR_MODEL_API_KEY")